/**
 * AEJ (Arquivo Eletrônico de Jornada) — consolidated treated journey.
 * Generated by the treatment module; must be signed by the employer (ICP-Brasil).
 * Adjustments never overwrite AFD originals — they appear here as treatment rows.
 */

import { createHash } from 'crypto';
import {
  CRLF,
  DIGITAL_SIGNATURE_TRAILER,
  crc16Kermit,
  employerIdTypeAndNumber,
  formatAfdDate,
  formatAfdDateTime,
  onlyDigits,
  padLeft,
  padRight,
} from './fiscal-utils';

export type AejMarkRow = {
  nsr: number;
  employeeCpf: string;
  markAt: Date;
  /** E=entrada S=saída D=início intervalo F=fim intervalo */
  markType: 'E' | 'S' | 'D' | 'F';
  /** Original AFD NSR this treated mark refers to */
  sourceNsr?: number;
  treated: boolean;
  notes?: string;
};

export type AejAdjustmentRow = {
  employeeCpf: string;
  date: Date;
  /** absence | medical | time_bank | manual_insert | other */
  kind: string;
  minutes?: number;
  notes?: string;
  relatedNsr?: number;
};

export type AejBuildInput = {
  employerTaxId: string;
  employerLegalName: string;
  periodStart: Date;
  periodEnd: Date;
  generatedAt: Date;
  marks: AejMarkRow[];
  adjustments: AejAdjustmentRow[];
};

function appendCrc(lineWithoutCrc: string): string {
  return lineWithoutCrc + crc16Kermit(lineWithoutCrc);
}

function buildHeader(input: AejBuildInput): string {
  const { type, number } = employerIdTypeAndNumber(input.employerTaxId);
  const body =
    '000000000' +
    '1' +
    type +
    number +
    padRight(input.employerLegalName, 150) +
    formatAfdDate(input.periodStart) +
    formatAfdDate(input.periodEnd) +
    formatAfdDateTime(input.generatedAt) +
    '001'; // AEJ layout version
  return appendCrc(body);
}

function mapType(t: AejMarkRow['markType']): string {
  return t;
}

function buildMarkLine(row: AejMarkRow, seq: number): string {
  const body =
    padLeft(String(seq), 9) +
    '2' +
    padLeft(onlyDigits(row.employeeCpf), 12) +
    formatAfdDateTime(row.markAt) +
    mapType(row.markType) +
    (row.treated ? '1' : '0') +
    padLeft(String(row.sourceNsr || row.nsr), 9) +
    padRight(row.notes || '', 100);
  return appendCrc(body);
}

function buildAdjustmentLine(row: AejAdjustmentRow, seq: number): string {
  const body =
    padLeft(String(seq), 9) +
    '3' +
    padLeft(onlyDigits(row.employeeCpf), 12) +
    formatAfdDate(row.date) +
    padRight(row.kind, 20) +
    padLeft(String(row.minutes ?? 0), 6) +
    padLeft(String(row.relatedNsr || 0), 9) +
    padRight(row.notes || '', 100);
  return appendCrc(body);
}

export type AejBuildResult = {
  content: string;
  fileName: string;
  sha256File: string;
};

export function clockTypeToAej(type: string): AejMarkRow['markType'] {
  if (type === 'in') return 'E';
  if (type === 'out') return 'S';
  if (type === 'break_start') return 'D';
  return 'F';
}

export function buildAej(input: AejBuildInput): AejBuildResult {
  const lines: string[] = [buildHeader(input)];
  let seq = 1;

  for (const mark of input.marks) {
    lines.push(buildMarkLine(mark, seq++));
  }
  for (const adj of input.adjustments) {
    lines.push(buildAdjustmentLine(adj, seq++));
  }

  lines.push(DIGITAL_SIGNATURE_TRAILER);
  const content = lines.join(CRLF) + CRLF;
  const { number } = employerIdTypeAndNumber(input.employerTaxId);

  return {
    content,
    fileName: `AEJ${number}.txt`,
    sha256File: createHash('sha256').update(content, 'latin1').digest('hex'),
  };
}
