/**
 * AEJ (Arquivo Eletrônico de Jornada) — Portaria MTP 671/2021, leiaute versão 002.
 * Pipe-delimited (|), ISO-8859-1, CRLF. Generated by PTRP (Puncto).
 * Signed by Puncto developer certificate (CAdES detached .p7s) — not employer PFX.
 */

import { createHash } from 'crypto';
import {
  CRLF,
  DIGITAL_SIGNATURE_TRAILER,
  employerIdTypeAndNumber,
  formatAfdDate,
  formatAfdDateTime,
  onlyDigits,
} from './fiscal-utils';

export const AEJ_LAYOUT_VERSION = '002';

export type AejVinculo = {
  idtVinculoAej: number;
  cpf11: string;
  nome: string;
  esocialRegistration?: string | null;
};

export type AejHorarioContratual = {
  codHorContratual: string;
  durJornadaMinutes: number;
  /** pairs of entry/exit as HHmm */
  pairs: Array<{ entrada: string; saida: string }>;
};

export type AejMarcacao = {
  idtVinculoAej: number;
  dataHoraMarc: Date;
  idRepAej: number;
  /** E entrada | S saída | D desconsiderada */
  tpMarc: 'E' | 'S' | 'D';
  seqEntSaida: number;
  /** O original | I inclusão manual | P pré | X exceção | T outras */
  fonteMarc: 'O' | 'I' | 'P' | 'X' | 'T';
  codHorContratual?: string;
  motivo?: string;
};

export type AejAusencia = {
  idtVinculoAej: number;
  /** 1 DSR | 2 falta | 3 banco horas | 4 folga feriado */
  tipoAusenOuComp: '1' | '2' | '3' | '4';
  data: Date;
  qtMinutos?: number;
  tipoMovBH?: '1' | '2';
};

export type AejBuildInput = {
  employerTaxId: string;
  employerLegalName: string;
  periodStart: Date;
  periodEnd: Date;
  generatedAt: Date;
  caepf?: string;
  cno?: string;
  inpiId?: string;
  vinculos: AejVinculo[];
  horarios: AejHorarioContratual[];
  marcacoes: AejMarcacao[];
  ausencias?: AejAusencia[];
  ptrp?: {
    nomeProg?: string;
    versaoProg?: string;
    developerTaxId?: string;
    developerName?: string;
    developerEmail?: string;
  };
};

const DEFAULT_INPI = onlyDigits(
  process.env.PUNCTO_AFD_INPI_ID || process.env.PUNCTO_INPI_ID || ''
).padStart(17, '0');
const DEFAULT_DEV_CNPJ = onlyDigits(
  process.env.PUNCTO_VENDOR_CNPJ || process.env.PUNCTO_MANUFACTURER_CNPJ || ''
);
const DEFAULT_DEV_NAME =
  process.env.PUNCTO_VENDOR_LEGAL_NAME || 'Puncto Servicos de Tecnologia Ltda.';
const DEFAULT_DEV_EMAIL = process.env.PUNCTO_VENDOR_EMAIL || 'contato@puncto.com.br';

function pipe(fields: Array<string | number>): string {
  return fields.map((f) => String(f ?? '')).join('|');
}

function sanitizeAej(value: string, max: number): string {
  return (value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\|/g, ' ')
    .slice(0, max);
}

function hhmm(value: string): string {
  const d = onlyDigits(value);
  if (d.length === 4) return d;
  if (d.length === 3) return d.padStart(4, '0');
  // "08:00" → 0800
  const m = value.match(/(\d{1,2}):(\d{2})/);
  if (m) return `${m[1].padStart(2, '0')}${m[2]}`;
  return d.padStart(4, '0').slice(0, 4);
}

export type AejBuildResult = {
  content: string;
  fileName: string;
  sha256File: string;
  layoutVersion: typeof AEJ_LAYOUT_VERSION;
  counts: Record<string, number>;
};

export function clockTypeToAejMark(type: string): 'E' | 'S' {
  if (type === 'in' || type === 'break_end') return 'E';
  return 'S';
}

export function buildAej(input: AejBuildInput): AejBuildResult {
  const { type } = employerIdTypeAndNumber(input.employerTaxId);
  // idtEmpregador: 11 or 14 without left-pad requirement beyond natural length
  const idtEmpregador =
    type === '2'
      ? onlyDigits(input.employerTaxId).padStart(11, '0').slice(-11)
      : onlyDigits(input.employerTaxId).padStart(14, '0').slice(-14);

  const lines: string[] = [];
  const counts: Record<string, number> = {
    '01': 0,
    '02': 0,
    '03': 0,
    '04': 0,
    '05': 0,
    '06': 0,
    '07': 0,
    '08': 0,
  };

  // 01 — Cabeçalho
  lines.push(
    pipe([
      '01',
      type,
      idtEmpregador,
      onlyDigits(input.caepf || '').padStart(14, '0').slice(0, 14) || '0'.repeat(14),
      onlyDigits(input.cno || '').padStart(12, '0').slice(0, 12) || '0'.repeat(12),
      sanitizeAej(input.employerLegalName, 150),
      formatAfdDate(input.periodStart),
      formatAfdDate(input.periodEnd),
      formatAfdDateTime(input.generatedAt),
      AEJ_LAYOUT_VERSION,
    ])
  );
  counts['01']++;

  // 02 — REP-P
  const idRepAej = 1;
  const nrRep = (input.inpiId ? onlyDigits(input.inpiId) : DEFAULT_INPI)
    .padStart(17, '0')
    .slice(-17);
  lines.push(pipe(['02', idRepAej, '3', nrRep]));
  counts['02']++;

  // 03 — Vínculos
  for (const v of input.vinculos) {
    lines.push(
      pipe([
        '03',
        v.idtVinculoAej,
        onlyDigits(v.cpf11).padStart(11, '0').slice(-11),
        sanitizeAej(v.nome, 150),
      ])
    );
    counts['03']++;
  }

  // 04 — Horário contratual
  for (const h of input.horarios) {
    const fields: Array<string | number> = [
      '04',
      sanitizeAej(h.codHorContratual, 30),
      h.durJornadaMinutes,
    ];
    for (const pair of h.pairs) {
      fields.push(hhmm(pair.entrada), hhmm(pair.saida));
    }
    lines.push(pipe(fields));
    counts['04']++;
  }

  // 05 — Marcações
  for (const m of input.marcacoes) {
    lines.push(
      pipe([
        '05',
        m.idtVinculoAej,
        formatAfdDateTime(m.dataHoraMarc),
        m.idRepAej || idRepAej,
        m.tpMarc,
        String(m.seqEntSaida).padStart(3, '0'),
        m.fonteMarc,
        m.codHorContratual ? sanitizeAej(m.codHorContratual, 30) : '',
        m.motivo ? sanitizeAej(m.motivo, 150) : '',
      ])
    );
    counts['05']++;
  }

  // 06 — Matrícula eSocial (quando informada)
  for (const v of input.vinculos) {
    if (!v.esocialRegistration) continue;
    lines.push(
      pipe(['06', v.idtVinculoAej, sanitizeAej(v.esocialRegistration, 30)])
    );
    counts['06']++;
  }

  // 07 — Ausências / BH
  for (const a of input.ausencias || []) {
    lines.push(
      pipe([
        '07',
        a.idtVinculoAej,
        a.tipoAusenOuComp,
        formatAfdDate(a.data),
        a.qtMinutos != null ? a.qtMinutos : '',
        a.tipoMovBH || '',
      ])
    );
    counts['07']++;
  }

  // 08 — PTRP
  const ptrp = input.ptrp || {};
  const devTax = onlyDigits(ptrp.developerTaxId || DEFAULT_DEV_CNPJ);
  const tpIdtDesenv: '1' | '2' = devTax.length <= 11 && devTax.length > 0 ? '2' : '1';
  lines.push(
    pipe([
      '08',
      sanitizeAej(ptrp.nomeProg || 'Puncto PTRP', 150),
      sanitizeAej(ptrp.versaoProg || '1.0.0', 8),
      tpIdtDesenv,
      tpIdtDesenv === '2'
        ? devTax.padStart(11, '0').slice(-11)
        : (devTax || '0').padStart(14, '0').slice(-14),
      sanitizeAej(ptrp.developerName || DEFAULT_DEV_NAME, 150),
      sanitizeAej(ptrp.developerEmail || DEFAULT_DEV_EMAIL, 50),
    ])
  );
  counts['08']++;

  // 99 — Trailer
  lines.push(
    pipe([
      '99',
      counts['01'],
      counts['02'],
      counts['03'],
      counts['04'],
      counts['05'],
      counts['06'],
      counts['07'],
      counts['08'],
    ])
  );

  lines.push(DIGITAL_SIGNATURE_TRAILER);

  const content = lines.join(CRLF) + CRLF;
  const fileName = `AEJ${idtEmpregador}.txt`;

  return {
    content,
    fileName,
    sha256File: createHash('sha256').update(content, 'latin1').digest('hex'),
    layoutVersion: AEJ_LAYOUT_VERSION,
    counts,
  };
}

/** @deprecated */
export function clockTypeToAej(type: string): 'E' | 'S' | 'D' | 'F' {
  if (type === 'in') return 'E';
  if (type === 'out') return 'S';
  if (type === 'break_start') return 'D';
  return 'F';
}
